export enum PLATFORM_TYPES {
  MOBILE = 'MOBILE',
  WEB = 'WEB',
}

export enum NOTIFICATION_TYPES {
  NEW_ARTICLE = 'NEW_ARTICLE',
  NEW_COMMENT = 'NEW_COMMENT',
  NEW_COMMENT_LIKE = 'NEW_COMMENT_LIKE',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_POST_LIKE = 'NEW_POST_LIKE',
  NEW_MENTION = 'NEW_MENTION',
  NEW_REPLY = 'NEW_REPLY',
  PRODUCT_ANNOUNCEMENTS = 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS = 'SIMILAR_PROJECTS',
}

export enum PROJECT_SORT_TYPES {
  POPULAR = 'POPULAR',
}

export enum FILE_TYPES {
  IMAGE = 'IMAGE',
}

export enum TOAST_TYPES {
  DEFAULT = 'DEFAULT',
  NETWORK = 'NETWORK',
  SUCCESS = 'SUCCESS',
  SPAM = 'SPAM',
}

export const ERROR_CODES = {
  INVALID: 'REFRESH_TOKEN_INVALID',
  REVOKED: 'REFRESH_TOKEN_REVOKED',
  SPAM: 'SPAM',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
}
