export enum PLATFORM_TYPES {
  MOBILE = 'MOBILE',
  WEB = 'WEB',
}

export enum NOTIFICATION_TYPES {
  NEW_ARTICLE = 'NEW_ARTICLE',
  NEW_COMMENT = 'NEW_COMMENT',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_MENTION = 'NEW_MENTION',
  NEW_REPLY = 'NEW_REPLY',
  PRODUCT_ANNOUNCEMENTS = 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS = 'SIMILAR_PROJECTS',
}

export enum PROJECT_SORT_TYPES {
  POPULAR = 'POPULAR',
}

export enum FILE_TYPES {
  IMAGE = 'IMAGE',
}
