export const NOTIFICATION_TYPES = {
  NEW_ARTICLE: 'NEW_ARTICLE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_FOLLOWER: 'NEW_FOLLOWER',
  NEW_MENTION: 'NEW_MENTION',
  NEW_REPLY: 'NEW_REPLY',
  PRODUCT_ANNOUNCEMENTS: 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS: 'SIMILAR_PROJECTS',
}

export const PLATFORM_TYPES = {
  MOBILE: 'MOBILE',
  WEB: 'WEB',
}

export const DYNAMIC_LINK_TYPES = {
  USER: 'USER',
  PROJECT: 'PROJECT',
}

export const AUTH_PROVIDER_TYPES = {
  FACEBOOK: 'FACEBOOK',
}
