export const NOTIFICATION_TYPES = {
  NEW_ARTICLE: 'NEW_ARTICLE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_FOLLOWER: 'NEW_FOLLOWER',
  NEW_MENTION: 'NEW_MENTION',
  PRODUCT_ANNOUNCEMENTS: 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS: 'SIMILAR_PROJECTS',
}
