import { NOTIFICATION_TYPES } from './enums'

export const DEFAULT_NOTIFICATIONS = {
  [NOTIFICATION_TYPES.NEW_ARTICLE]: true,
  [NOTIFICATION_TYPES.NEW_COMMENT]: true,
  [NOTIFICATION_TYPES.NEW_FOLLOWER]: true,
  [NOTIFICATION_TYPES.NEW_MENTION]: true,
  [NOTIFICATION_TYPES.PRODUCT_ANNOUNCEMENTS]: true,
  [NOTIFICATION_TYPES.SIMILAR_PROJECTS]: true,
}
