export const NOTIFICATION_TYPES = {
  COMMENT_UPDATES: 'COMMENT_UPDATES',
  NEW_ARTICLE: 'NEW_ARTICLE',
  NEW_COMMENT_LIKE: 'NEW_COMMENT_LIKE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_FOLLOWER: 'NEW_FOLLOWER',
  NEW_MENTION: 'NEW_MENTION',
  NEW_POST_LIKE: 'NEW_POST_LIKE',
  NEW_REPLY: 'NEW_REPLY',
  PRODUCT_ANNOUNCEMENTS: 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS: 'SIMILAR_PROJECTS',
}

export const MAIL_TYPES = {
  WELCOME: 'welcome',
}

export const PLATFORM_TYPES = {
  MOBILE: 'MOBILE',
  WEB: 'WEB',
}

export const PROJECT_SORT_TYPES = {
  POPULAR: 'POPULAR',
  RECENT: 'RECENT',
}

export const SEARCH_TYPES = {
  MODELS: 'MODELS',
  PROJECTS: 'PROJECTS',
  USERS: 'USERS',
  HASHTAGS: 'HASHTAGS',
}

export const AUTH_PROVIDER_TYPES = {
  APPLE: 'APPLE',
  FACEBOOK: 'FACEBOOK',
  GOOGLE: 'GOOGLE',
}

export const FILE_TYPES = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
}

export const LIKE_TYPES = {
  COMMENT: 'COMMENT',
  POST: 'POST',
}

export const ERROR_CODES = {
  INVALID: 'REFRESH_TOKEN_INVALID',
  NOT_FOUND: 'NOT_FOUND',
  REVOKED: 'REFRESH_TOKEN_REVOKED',
  SPAM: 'SPAM',
}

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER',
}
