#!/bin/sh
concurrently \
  --kill-others-on-fail \
  --prefix "{name} >" \
  --names "start:packager    ,run:ios    ,watch:graphql" \
  -c "blue.bold,yellow.bold,magenta.bold" \
  "yarn start:packager" \
  "yarn run:ios" \
  "yarn watch:graphql"
