# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wrench' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'

  # Pods for Wrench
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'

  # Will try to install React when running `pod update`
  # pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  # pod 'RNRate', :path => '../node_modules/react-native-rate/ios'
  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

end
