# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Wrench' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'

  # Pods for Wrench
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'

  # Will try to install React when running `pod update`
  # pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  # pod 'RNRate', :path => '../node_modules/react-native-rate/ios'
  # pod 'RNScreens', :path => '../node_modules/react-native-screens'

end
