web:
  component: "@sls-next/serverless-component@1.16.0"
  inputs:
    domain: "wrench.cc"
    bucketName: wrench-web-edge
    build: true
      memory:
        defaultLambda: 2048
        apiLambda: 512
    cloudfront:
      defaults:
        forward:
          headers: ['CloudFront-Viewer-Country', 'Accept-Language']