 
web:
  component: ./infra/serverless-next
  inputs:
    domain: "wrench.cc"
    bucketName: wrench-web-edge
    build: true
    lambda:
      name: wrench-web #todo
      memory: 2048
    cloudfront:
      compress: true
      forward:
        headers: ['CloudFront-Viewer-Country', 'Accept-Language']
