web:
  component: "@sls-next/serverless-component@1.17.0-alpha.12"
  inputs:
    domain: "wrench.cc"
    bucketName: wrench-web-edge
    build: true
    memory: 2048
    cloudfront:
      defaults:
        forward:
          headers: ['CloudFront-Viewer-Country', 'Accept-Language']