web:
  component: "@sls-next/serverless-component@2.6.2"
  inputs:
    domain: "wrench.cc"
    bucketName: wrench-web-edge
    build: true
    defaultLambda:
      memory: 2048
      runtime: nodejs12.x
    cloudfront:
      compress: true
      defaults:
        forward:
          headers: ['CloudFront-Viewer-Country', 'Accept-Language']