web:
  component: ./infra/serverless-next-edge
  inputs:
    domain: "wrench.cc"
    bucketName: wrench-web-edge
    build: true
    defaultLambda:
      memory: 2048
      runtime: nodejs12.x
    apiLambda:
      memory: 2048
      runtime: nodejs12.x
    cloudfront:
      compress: true
      forward:
        headers: ['CloudFront-Viewer-Country', 'Accept-Language']
