#!/bin/sh

LOCAL_DOCKER="http://localhost:9200"
TARGET_ENV=$LOCAL_DOCKER

if [ "$1" ]
then
  echo "Using target" $1
  TARGET_ENV=$1
fi

curl -XPUT $TARGET_ENV'/klapp-search-1' -H 'Content-Type: application/json' -d'
{
  "aliases" : {
    "klapp-search" : { }
  },
  "settings": {
    "index" : {
      "number_of_shards" : 6,
      "number_of_replicas" : 1
    },
    "analysis": {
      "tokenizer": {
        "merchant_name_tokenizer": {
          "type": "edge_ngram",
          "min_gram": 1,
          "max_gram": 20,
          "token_chars": []
        },
        "line_item_name_tokenizer": {
          "type": "ngram",
          "min_gram": 1,
          "max_gram": 2,
          "token_chars": ["letter", "digit", "symbol"]
        }
      },
      "analyzer": {
        "merchant_name_analyzer": {
          "filter": ["lowercase"],
          "tokenizer": "merchant_name_tokenizer"
        },
        "line_item_name_analyzer": {
          "filter": ["lowercase"],
          "tokenizer": "standard"
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "dynamic" : "false",
      "properties": {
        "generationId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "indexedAt": {
          "type": "date"
        },
        "lineItems": {
          "properties": {
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "line_item_name_analyzer",
              "search_analyzer": "line_item_name_analyzer"
            },
            "price": {
              "properties": {
                "amount": {
                  "type": "long"
                },
                "currency": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                }
              }
            }
          }
        },
        "merchant": {
          "properties": {
            "displayName": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              },
              "analyzer": "merchant_name_analyzer",
              "search_analyzer": "merchant_name_analyzer"
            },
            "icon": {
              "properties": {
                "contentType": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "hash": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "height": {
                  "type": "long"
                },
                "url": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "width": {
                  "type": "long"
                },
                "x1": {
                  "properties": {
                    "height": {
                      "type": "long"
                    },
                    "url": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "width": {
                      "type": "long"
                    }
                  }
                },
                "x2": {
                  "properties": {
                    "height": {
                      "type": "long"
                    },
                    "url": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "width": {
                      "type": "long"
                    }
                  }
                },
                "x3": {
                  "properties": {
                    "height": {
                      "type": "long"
                    },
                    "url": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "width": {
                      "type": "long"
                    }
                  }
                }
              }
            }
          }
        },
        "personaId": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "purchasedAt": {
          "type": "date",
          "format": "date_time_no_millis"
        },
        "totalAmount": {
          "properties": {
            "amount": {
              "type": "long"
            },
            "currency": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "type": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}
'
