version: '3.7'
services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:11.1
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     PGDATA: /var/lib/postgresql/data/pgdata
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
volumes:
  esdata:
