version: '3.7'
services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:11.1
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
volumes:
  esdata:
