service:
  name: image-resizer

plugins:
  - serverless-plugin-ncc

custom:
  ncc:
    minify: true

provider:
  name: aws
  region: us-east-1 # Lambda@Edge restriction
  runtime: nodejs8.10 # Lambda@Edge restriction
