#!/usr/bin/env bash

set -uex

# Relative to fastlane tool
TARGET_FILE=../packages/mobile/.env

echo "GRAPHQL_URL=${GRAPHQL_URL}" >> ${TARGET_FILE}
echo "ENVIRONMENT=${ENVIRONMENT}" >> ${TARGET_FILE}
echo "SENTRY_DSN=${SENTRY_DSN}" >> ${TARGET_FILE}
echo "MAPBOX_API_KEY=${MAPBOX_API_KEY}" >> ${TARGET_FILE}