# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wrench' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wrench
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  platform :ios, '9.0'
  pod 'react-native-video', :path => '../node_modules/react-native-video'
  pod 'RNShare', :path => '../node_modules/react-native-share'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  #pod 'RNReactNativeHapticFeedback', :path => '../node_modules/react-native-haptic-feedback'
  
end
