require "json"

xcodeproj = "packages/mobile/ios/Wrench.xcodeproj"
workspace = "packages/mobile/ios/Wrench.xcworkspace"
android = "packages/mobile/android"

package = File.read("../package.json")
version = JSON.parse(package)["version"]
build_number = ENV["BUILD_NUMBER"]

# def slack_notification()
#   slack(
#     message: "Wrench (iOS)",
#     channel: "#release",
#     payload: { 
#       "Build ##{build_number}" => "Succeeded.",
#       "Version ##{version}" => "Succeeded.",
#       "Build Date" => Time.new.to_s,
#       "Built by" => "Github Actions",
#     },
#     default_payloads: [:git_branch, :git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
#     attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
#       thumb_url: "http://example.com/path/to/thumb.png",
#     }
#   )
# end

# iOS Beta
lane :ios do
  # setup_ci(force: true)
  match(app_identifier: 'cc.wrench.app', type: 'appstore', readonly: true)
  increment_build_number({ build_number: build_number, xcodeproj: xcodeproj })
  increment_version_number({ version_number: version, xcodeproj: xcodeproj })
  # # sh "actions/create-env"
  gym(
    workspace: workspace,
    scheme: "Wrench",
    clean: true,
    export_method: "app-store",
    build_path: "./.builds",
    output_directory: "./.builds"
  )

  changelog = read_changelog
  pilot(skip_waiting_for_build_processing: true, changelog: changelog)
  stamp_changelog(section_identifier: "Build #{build_number}")
  # slack_notification(platform: 'iOS', version: version)
end

# Android Beta
lane :android do
  sh "actions/create-env"
  gradle(
    task: 'clean',
    project_dir: android
  )
  gradle(
    project_dir: android,
    task: 'bundle',
    build_type: 'Release',
    print_command: false,
    properties: {
      "versionCode" => build_number,
      "versionName" => version,
    }
  )
  supply(
    track: 'internal',
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
  # slack_notification(platform: 'Android', version: version)
end
