# Disable Sending anonymous analytics information
opt_out_usage 

require "json"
require './utils/slack'  

xcodeproj = "packages/mobile/ios/Wrench.xcodeproj"
workspace = "packages/mobile/ios/Wrench.xcworkspace"
android = "packages/mobile/android"

package = File.read("../package.json")
version = JSON.parse(package)["version"]
build_number = ENV["BUILD_NUMBER"] || "1"

# https://appstoreconnect.apple.com/access/api
app_store_connect_api_key(
  key_id: "PLF7386UJG",
  issuer_id: "69a6de92-9171-47e3-e053-5b8c7c11a4d1",
  key_filepath: 'AuthKey_PLF7386UJG.p8'
)

# Slack error message
error do |lane, exception|
  slack_notification(
    lane.to_s == 'ios' ? 'iOS' : 'Android',
    version, 
    build_number,
    false,
  )
end

# iOS Beta
lane :ios do
  setup_ci(force: true)
  cocoapods(
    podfile: "packages/mobile/ios/Podfile"
  )
  # TODO: Use env from github actions (MATCH_GIT_BASIC_AUTHORIZATION)
  match(app_identifier: 'cc.wrench.app', type: 'appstore', readonly: true, git_basic_authorization: 'cG9udHVzYWI6ZWU1YTVlNTNmYTU0Mzc4ZTEyYWQwYTNjZDQzZDYzOGQzOTNkN2FkNQ==1')
  increment_build_number({ build_number: build_number, xcodeproj: xcodeproj })
  # TODO: Change to version if possible to reset in Apple
  increment_version_number({ version_number: build_number, xcodeproj: xcodeproj })
  sh "actions/create-env"
  gym(
    workspace: workspace,
    scheme: "Wrench",
    clean: true,
    export_method: "app-store",
    build_path: "./.builds",
    output_directory: "./.builds"
  )
  pilot(skip_waiting_for_build_processing: true)
  slack_notification(
   'iOS', 
   build_number,
   version,
   true
  )
end

# Android Beta
lane :android do
  sh "actions/create-env"
  gradle(
    project_dir: android,
    task: 'bundle',
    build_type: 'Release',
    print_command: false,
    properties: {
      "versionCode" => build_number,
      "versionName" => version,
    }
  )
  supply(
    track: 'internal',
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
  slack_notification(
    'Android', 
    build_number,
    version,
    true
  )
end
