service: 'resizer'

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  deploymentBucket: wrench-image-resizer
  memorySize: 2048

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - serverless
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npm rm sharp && npm install --arch=x64 --platform=linux sharp

functions:
  OriginResponse:
    handler: handler.originResponse