service:
  name: image-resize

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  deploymentBucket: wrench-image-resize
  memorySize: 2048

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - serverless
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npm rm sharp && env npm_config_arch=x64 npm_config_platform=linux npm_config_target=8.10.0 npm install sharp

functions:
  OriginResponse:
    handler: handler.originResponse
