service: 'image-resize'

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  deploymentBucket: wrench-image-resize
  memorySize: 2048
  profile: wrench-api

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - serverless
    packager: 'yarn'
    packagerOptions:
      scripts:
        - npm rm sharp && env npm_config_arch=x64 npm_config_platform=linux npm_config_target=10.16.0 npm install sharp

functions:
  OriginResponse:
    handler: handler.originResponse
