export const SCREENS = {
  FEED: 'FEED',
  EXPLORE: 'EXPLORE',
  NOTIFICATIONS: 'NOTIFICATIONS',
  ME: 'ME',
  PROJECT: 'PROJECT',
  FOLLOWERS: 'FOLLOWERS',
  USER: 'USER',
  POST: 'POST',
  COMMENTS: 'COMMENTS',
  WEBVIEW: 'WEBVIEW',
}
