// TODO Heights
export enum NAVIGATION {
  LIST_INSET_TOP = 0,
  TOP_BAR_HEIGHT = 60,
  STATUS_BAR_HEIGHT = 44,
  TOTAL_TOP_BAR_HEIGHT = 60 + 44,
  TAB_HEIGHT = 60,
}

export enum SCREENS {
  INITIALIZING = 'INITIALIZING',
  ONBOARDING = 'ONBOARDING',
  FEED = 'FEED',
  EXPLORE = 'EXPLORE',
  COMMENTS = 'COMMENTS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ME = 'ME',
  PROJECT = 'PROJECT',
  FOLLOWERS = 'FOLLOWERS',
  USER = 'USER',
  POST = 'POST',
  COMMENTS = 'COMMENTS',
  WEBVIEW = 'WEBVIEW',
  SIGN_IN = 'SIGN_IN',
  ADD_PROJECT_MODEL = 'ADD_PROJECT_MODEL',
  ADD_PROJECT_TYPE = 'ADD_PROJECT_TYPE',
  ADD_PROJECT = 'ADD_PROJECT',
  ADD_MEDIA = 'ADD_MEDIA',
  ADD_POST = 'ADD_POST',
  EDIT_PROJECT = 'EDIT_PROJECT',
  SETTINGS = 'SETTINGS',
  MENTION = 'MENTION',
}

export enum SCREEN_PATH {
  NOTIFICATIONS = 'notification',
  POST = 'post',
  PROJECT = 'project',
}
