import { hasNotch, isAndroid } from 'utils/platform'

export enum NAVIGATION {
  LIST_INSET_TOP = 30,
  TOP_BAR_HEIGHT = 60,
  STATUS_BAR_HEIGHT = isAndroid ? 10 : hasNotch ? 44 : 20,
  TOTAL_TOP_BAR_HEIGHT = hasNotch ? 104 : 80,
  TAB_HEIGHT = 60,
  LIST_OFFSET = hasNotch ? 120 : 90,
}

export const BOTTOM_TABS_ID = 'BottomTabs'

export enum SCREENS {
  INITIALIZING = 'INITIALIZING',
  ONBOARDING = 'ONBOARDING',
  ARTICLES = 'ARTICLES',
  FEED = 'FEED',
  EXPLORE = 'EXPLORE',
  COMMENTS = 'COMMENTS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ME = 'ME',
  PROJECT = 'PROJECT',
  FOLLOWERS = 'FOLLOWERS',
  USER = 'USER',
  POST = 'POST',
  COMMENTS = 'COMMENTS',
  WEBVIEW = 'WEBVIEW',
  SIGN_IN = 'SIGN_IN',
  ADD_PROJECT_MODEL = 'ADD_PROJECT_MODEL',
  ADD_PROJECT_TYPE = 'ADD_PROJECT_TYPE',
  ADD_PROJECT = 'ADD_PROJECT',
  ADD_MEDIA = 'ADD_MEDIA',
  ADD_POST = 'ADD_POST',
  EDIT_PROJECT = 'EDIT_PROJECT',
  SETTINGS = 'SETTINGS',
  MENTION = 'MENTION',
  EDIT_MODEL = 'EDIT_MODEL',
}

export enum SCREEN_PATH {
  NOTIFICATIONS = 'notification',
  POST = 'post',
  PROJECT = 'project',
}

export enum STATUS_BAR {
  LIGHT = 'light',
  DARK = 'dark',
}
