import { getStatusBarHeight } from 'react-native-status-bar-height'

export const LIST_INSET_TOP = 30
export const STATUS_BAR_HEIGHT = getStatusBarHeight()
export const TOP_BAR_HEIGHT = 60
export const TOTAL_TOP_BAR_HEIGHT = STATUS_BAR_HEIGHT + TOP_BAR_HEIGHT
export const CONTENT_INSET = TOTAL_TOP_BAR_HEIGHT + LIST_INSET_TOP

export const BOTTOM_TABS_ID = 'BOTTOM_TABS'

export enum SCREENS {
  ADD_LOCATION = 'ADD_LOCATION',
  ADD_MEDIA = 'ADD_MEDIA',
  ADD_POST = 'ADD_POST',
  ADD_POST_TO_COLLECTION = 'ADD_POST_TO_COLLECTION',
  ADD_PROJECT = 'ADD_PROJECT',
  ADD_PROJECT_MODEL = 'ADD_PROJECT_MODEL',
  ADD_PROJECT_TYPE = 'ADD_PROJECT_TYPE',
  BOOKMARKS = 'BOOKMARKS',
  COMMENTS = 'COMMENTS',
  COLLECTIONS = 'COLLECTIONS',
  EDIT_MODEL = 'EDIT_MODEL',
  EDIT_PROFILE = 'EDIT_PROFILE',
  EDIT_PROJECT = 'EDIT_PROJECT',
  EDIT_COLLECTION = 'EDIT_COLLECTION',
  EXPLORE = 'EXPLORE',
  FEED = 'FEED',
  FOLLOWERS = 'FOLLOWERS',
  INITIALIZING = 'INITIALIZING',
  INSPIRATION = 'INSPIRATION',
  ME = 'ME',
  MENTION = 'MENTION',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ONBOARDING = 'ONBOARDING',
  OTHER_SIGN_IN_OPTIONS = 'OTHER_SIGN_IN_OPTIONS',
  POST = 'POST',
  PROJECT = 'PROJECT',
  SETTINGS = 'SETTINGS',
  SIGN_IN = 'SIGN_IN',
  USER = 'USER',
  WEBVIEW = 'WEBVIEW',
  EDIT_POST = 'EDIT_POST',
  CATEGORIES = 'CATEGORIES',
  EMPTY = 'EMPTY',
  PROJECT_SUGGESTIONS = 'PROJECT_SUGGESTIONS',
  PUSH_NOTIFICATIONS = 'PUSH_NOTIFICATIONS',
  HASHTAG = 'HASHTAG',
  LIKES = 'LIKES',
  HALFPANEL = 'HALFPANEL',
}

export enum STATUS_BAR {
  DARK = 'dark',
  LIGHT = 'light',
}

export enum TABS_INDEX {
  FEED = 0,
  EXPLORE = 1,
  ADD = 2,
  NOTIFICATIONS = 3,
  ME = 4,
}
