service: 'articles'

custom:
  bucket: wrench-files

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket: wrench-articles
  profile: wrench-api
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  bikeexif:
    handler: src/providers/bikeexif.default
    events:
      - schedule: rate(2 hours)

  pipeburn:
    handler: src/providers/pipeburn.default
    events:
      - schedule: rate(2 hours)

  silodrome:
    handler: src/providers/silodrome.default
    events:
      - schedule: rate(2 hours)

  bikebound:
    handler: src/providers/bikebound.default
    events:
      - schedule: rate(4 hours)

  thebikeshed:
    handler: src/providers/thebikeshed.default
    events:
      - schedule: rate(4 hours)

  caferacerdreams:
    handler: src/providers/caferacerdreams.default
    events:
      - schedule: rate(6 hours)

  hookie:
    handler: src/providers/hookie.default
    events:
      - schedule: rate(6 hours)

  bikebrewers:
    handler: src/providers/bikebrewers.default
    events:
      - schedule: rate(4 hours)

  returnofthecaferacers:
    handler: src/providers/returnofthecaferacers.default
    events:
      - schedule: rate(2 hours)

  bonnefication:
    handler: src/providers/bonnefication.default
    events:
      - schedule: rate(4 hours)

  themotoblogs:
    handler: src/providers/themotoblogs.default
    events:
      - schedule: rate(4 hours)

  motorcyclistonline:
    handler: src/providers/motorcyclistonline.default
    events:
      - schedule: rate(4 hours)

  deuscustoms:
    handler: src/providers/deuscustoms.default
    events:
      - schedule: rate(4 hours)
