export const NOTIFICATIONS_COLUMN = 'notifications'

export const NOTIFICATION_TYPES = {
  NEW_ARTICLE: 'newArticle',
  NEW_COMMENT: 'newComment',
  NEW_FOLLOWER: 'newFollower',
  NEW_MENTION: 'newMention',
  PRODUCT_ANNOUNCEMENTS: 'productAnnouncements',
  SIMILAR_PROJECTS: 'similarProjects',
}

export const DEFAULT_NOTIFICATIONS = {
  [NOTIFICATION_TYPES.NEW_ARTICLE]: true,
  [NOTIFICATION_TYPES.NEW_COMMENT]: true,
  [NOTIFICATION_TYPES.NEW_FOLLOWER]: true,
  [NOTIFICATION_TYPES.NEW_MENTION]: true,
  [NOTIFICATION_TYPES.PRODUCT_ANNOUNCEMENTS]: true,
  [NOTIFICATION_TYPES.SIMILAR_PROJECTS]: true,
}
