export const NOTIFICATION_TYPES = {
  NEW_ARTICLE: 'NEW_ARTICLE',
  NEW_COMMENT: 'NEW_COMMENT',
  NEW_FOLLOWER: 'NEW_FOLLOWER',
  NEW_MENTION: 'NEW_MENTION',
  NEW_REPLY: 'NEW_REPLY',
  PRODUCT_ANNOUNCEMENTS: 'PRODUCT_ANNOUNCEMENTS',
  SIMILAR_PROJECTS: 'SIMILAR_PROJECTS',
}

export const PLATFORM_TYPES = {
  MOBILE: 'MOBILE',
  WEB: 'WEB',
}

export const DYNAMIC_LINK_TYPES = {
  PROJECT: 'PROJECT',
  USER: 'USER',
}

export const PROJECT_SORT_TYPES = {
  POPULAR: 'POPULAR',
}

export const SEARCH_TYPES = {
  MODELS: 'MODELS',
  PROJECTS: 'PROJECTS',
  USERS: 'USERS',
}

export const AUTH_PROVIDER_TYPES = {
  FACEBOOK: 'FACEBOOK',
}

export const FILE_TYPES = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
}

export const REFRESH_TOKEN_CODES = {
  INVALID: 'REFRESH_TOKEN_INVALID',
  REVOKED: 'REFRESH_TOKEN_REVOKED',
}
