name: 'Deploy Admin'
on:
  push:
    branches:
      - master
    paths:
      - 'packages/admin/**'
      - 'packages/common/**'
      - 'packages/ui/**'

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Uses Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Build admin
        run: |
          echo Building admin...
          cd packages/admin
          yarn
          yarn build

      - name: Push to AWS
        run: |
           cd packages/admin
           yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}