name: 'Deploy Android to Internal channel'
on:
  push:
    branches:
      - master

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build app
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'android'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}

