name: 'Deploy Codepush'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'packages/mobile/ios/**'
      - 'packages/mobile/android/**'
    paths:
      - 'packages/mobile/**'
      - 'packages/common/**'
      - 'packages/ui/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -d Production
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}