name: 'Deploy workflow'
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        # with:
        #   fetch-depth: 1

      - uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: "719104767000"
          # repo: docker/repo
          region: eu-west-1
          tags: latest,${{ github.sha }}
          path: packages/api
          # create_repo: true
          extra_build_args: "--verbose"