name: Deploy
push: 
  branches: 
    - master
  jobs: 
    build: 
      runs-on: ubuntu-latest
      steps: 
        - 
          name: "Checkout master"
        - 
          uses: actions/checkout@v1.1.0
        - 
          name: "Publish to Registry"
        - 
          env: 
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          uses: mr-smithers-excellent/docker-build-push@v1.0
          with: 
            dockerfile: Dockerfile.ci
            image: api
            registry: 719104767000.dkr.ecr.eu-west-1.amazonaws.com
            tag: latest
