on:
name: Deploy
push:
  branches:
  - master
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout master
      - uses: actions/checkout@v1.1.0
      - name: Publish to Registry
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: api
          tag: latest
          dockerfile: Dockerfile.ci
          registry: 719104767000.dkr.ecr.eu-west-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}