name: 'Deploy workflow'
on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: API Build & Push to AWS ECR
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          IMAGE_NAME: "api"
          BUILD_PATH: "packages/api/Dockerfile"
          # TAG_NAME: "v0.0.1"
          LATEST: "true"
    # - name: Checkout master
    # - uses: actions/checkout@v1.1.0
    # - name: Publish to Registry
    # - uses: mr-smithers-excellent/docker-build-push@v1.0
    #   with:
    #     image: api
    #     tag: latest
    #     dockerfile: packages/api/Dockerfile
    #     registry: 719104767000.dkr.ecr.eu-west-1.amazonaws.com
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}