name: 'Deploy workflow'
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest
    steps:
    - name: ECR Login
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: eu-west-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        entrypoint: /bin/sh
        args: -c "aws ecr get-login --no-include-email | sh"
    - uses: actions/checkout@master
    - name: Build Container
      uses: actions/docker/cli@master
      with:
        args: '"build -t 719104767000.dkr.ecr.eu-west-1.amazonaws.com/api:latest
          -t 719104767000.dkr.ecr.eu-west-1.amazonaws.com/api:latest -f packages/api/Dockerfile ."'
    - name: Push Container
      uses: actions/docker/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IMAGE_URI: 719104767000.dkr.ecr.eu-west-1.amazonaws.com/api:latest
      with:
        entrypoint: /bin/sh
        args: -c "docker push $IMAGE_URI"


  # deploy:
  #   needs: build
  #   name: Deploy API
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: ECR Login
  #     uses: actions/aws/cli@master
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_REGION: eu-west-1
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     with:
  #       entrypoint: /bin/sh
  #       args: -c "aws ecr get-login --no-include-email | sh"
  #   - name: Pull ECS Deployer
  #     uses: actions/docker/cli@master
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       IMAGE_URI: 719104767000.dkr.ecr.eu-west-1.amazonaws.com/api:master
  #     with:
  #       entrypoint: /bin/sh
  #       args: -c "docker pull $IMAGE_URI"
  #   - name: Deploy to ECS
  #     env:
  #       AWS_DEPLOY_PROD: ${{ secrets.AWS_DEPLOY_PROD }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       IMAGE_URI: 719104767000.dkr.ecr.eu-west-1.amazonaws.com/api:master
  #       CLUSTER: KILLERAPP-cluster-prod
  #       SERVICE: KILLERAPP-service-prod
  #       CONTAINER: KILLERAPP
  #       VERSION: prod
  #     run: |
  #       docker run -e AWS_DEPLOY_PROD -e AWS_SECRET_ACCESS_KEY $IMAGE_URI /bin/bash -c "ecs_deploy.sh $CLUSTER $SERVICE $CONTAINER $VERSION"









# name: 'Deploy workflow'
# on:
#   push:
#     branches:
#       - master

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#         with:
#           fetch-depth: 1

#       - name: API Build & Push to AWS ECR
#       - uses: mr-smithers-excellent/docker-build-push@v1.0
#       with:
#         image: api
#         tag: latest
#         dockerfile: packages/api/Dockerfile
#         registry: 719104767000.dkr.ecr.eu-west-1.amazonaws.com
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
