name: 'Deploy Apps'
on:
  push:
    branches:
      - master
    paths:
      - 'packages/mobile/**'
      - 'packages/common/**'
      - 'packages/ui/**'
      - 'fastlane/**'

jobs:
  version_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: "Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}   
     

  deploy:
    needs: version_tag
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.GITHUB_TOKEN}} 

      - name: Uses Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install -g yarn
      - name: Install dependencies
        run: |
          yarn install

      - name: Deploy Android
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'android'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Deploy iOS
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'ios'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}