name: 'Deploy Apps'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/mobile.yml'
      - 'fastlane/**'
      - 'packages/common/**'
      - 'packages/mobile/**'
      - 'packages/translations/**'
      - 'packages/ui/**'

jobs:
  version_tag:
    name: Version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Version Bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.GITHUB_TOKEN}} 
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
     
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: BUILD_NUMBER
          path: BUILD_NUMBER

  android:
    needs: version_tag
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby Setup for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.1'
          bundler-cache: true

      - name: Uses Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      
      - name: Install dependencies
        run: |
          yarn install

      # https://github.com/expo/expo-github-action/issues/20
      - name: Patching system watchers for the `ENOSPC` error...
        run: | 
          sudo sysctl fs.inotify.max_user_instances=524288 
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl fs.inotify.max_queued_events=524288
          sudo sysctl -p

      - name: Download build number
        uses: actions/download-artifact@v1
        with:
          name: BUILD_NUMBER
      
      - name: Restore build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      
      - name: Deploy Android
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          SLACK_URL: ${{secrets.SLACK_URL}}
          CODEPUSH_KEY_IOS_STAGING: ${{secrets.CODEPUSH_KEY_IOS_STAGING}}
          CODEPUSH_KEY_IOS_PRODUCTION: ${{secrets.CODEPUSH_KEY_IOS_PRODUCTION}}
          CODEPUSH_KEY_ANDROID_STAGING: ${{secrets.CODEPUSH_KEY_ANDROID_STAGING}}
          CODEPUSH_KEY_ANDROID_PRODUCTION: ${{secrets.CODEPUSH_KEY_ANDROID_PRODUCTION}}

  ios:
    needs: version_tag
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Ruby Setup for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.1'
          bundler-cache: true

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.3'

      - name: Uses Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Download build number
        uses: actions/download-artifact@v1
        with:
          name: BUILD_NUMBER

      - name: Restore build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Deploy iOS
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'ios'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}} 
          SPACESHIP_SKIP_2FA_UPGRADE: ${{secrets.SPACESHIP_SKIP_2FA_UPGRADE}} 
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}} 
          FASTLANE_SESSION: ${{secrets.FASTLANE_SESSION}}
          FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
          FASTLANE_USER: ${{secrets.FASTLANE_USER}}
          DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
          SLACK_URL: ${{secrets.SLACK_URL}}
          CODEPUSH_KEY_IOS_STAGING: ${{secrets.CODEPUSH_KEY_IOS_STAGING}}
          CODEPUSH_KEY_IOS_PRODUCTION: ${{secrets.CODEPUSH_KEY_IOS_PRODUCTION}}
          CODEPUSH_KEY_ANDROID_STAGING: ${{secrets.CODEPUSH_KEY_ANDROID_STAGING}}
          CODEPUSH_KEY_ANDROID_PRODUCTION: ${{secrets.CODEPUSH_KEY_ANDROID_PRODUCTION}}
