name: 'Deploy Apps'
on:
  push:
    branches:
      - master
    paths:
      - 'packages/mobile/**'
      - 'fastlane/**'

jobs:
  mobile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Uses Node.js 13
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install -g yarn

      - name: Build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.GITHUB_TOKEN}} 

      - name: "Version Bump"
        uses: tool3/bump@v1
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}   

      - name: Install dependencies
        run: |
          yarn install

      - name: Deploy Android
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'android'
          subdirectory: 'fastlane'
          skip-tracking: true
        env:
          GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # - name: Deploy iOS
      #   uses: maierj/fastlane-action@v1.2.0
      #   with:
      #     lane: 'ios'
      #     subdirectory: 'fastlane'
      #     skip-tracking: true
      #   env:
      #     GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
      #     SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      #     ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #     SENTRY_URL: ${{ secrets.SENTRY_URL }}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}