name: 'Deploy web'
on:
  push:
    branches:
      - master

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: 
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}

      - name: Push to AWS Lambda@edge
        run: 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}