name: 'Deploy Web'
on:
  push:
    branches:
      - master
    paths:
      - 'packages/web/**'
      - 'packages/common/**'
      - 'packages/ui/**'

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build web
        run: |
          echo Building web...
          cd packages/web
          yarn

      - name: Push to AWS Lambda@edge
        run: |
           cd packages/web
           yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          APPLE_REDIRECT_URI: ${{ secrets.APPLE_REDIRECT_URI }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}